/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "outline": "var(--color-outline)",
        "on-background": "var(--color-on-background)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "surface-tint": "var(--color-surface-tint)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "secondary-container": "var(--color-secondary-container)",
        "on-secondary": "var(--color-on-secondary)",
        "surface-container": "var(--color-surface-container)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "background": "var(--color-background)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "primary": "var(--color-primary)",
        "primary-container": "var(--color-primary-container)",
        "surface-variant": "var(--color-surface-variant)",
        "tertiary": "var(--color-tertiary)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "secondary": "var(--color-secondary)",
        "surface": "var(--color-surface)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-tertiary": "var(--color-on-tertiary)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-primary": "var(--color-on-primary)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-bright": "var(--color-surface-bright)",
        "inverse-surface": "var(--color-inverse-surface)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-surface": "var(--color-on-surface)",
        "surface-container-low": "var(--color-surface-container-low)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "error-container": "var(--color-error-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "error": "var(--color-error)",
        "surface-dim": "var(--color-surface-dim)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-error": "var(--color-on-error)",
        "on-error-container": "var(--color-on-error-container)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-container-highest": "var(--color-surface-container-highest)"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      spacing: {
        "sidebar-width": "260px",
        "container-padding": "24px",
        "card-gap": "16px",
        "gutter": "20px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
